# The working dir... output will be in the results subfolder of the workdir
workdir: "WORKDIR"

# temporary directory for intermediate files that are not saved
tempdir: "TEMP_DIR"

# tab delimited samples file ... should have the following 3 columns
# sampleName	groupName	path_to_R1_fastq	path_to_R2_fastq
samples: "WORKDIR/samples.tsv"

# select references .... host + viruses(comma-separated):
# select host: # options are hg38 or mm39
# host:       "hg38"
# additives:  "ERCC" # options are ERCC and BAC16Insert
# viruses:    "NC_009333.1"
host: "HOST"
additives: "ADDITIVES"
viruses: "VIRUSES"
# select viruses and other (ERCC/BAC): options are
# ERCC
# BAC16Insert
#
# | RefSeq  Sequence | RefSeq assembly accession | Notes                                                 |
# | ---------------- | ------------------------- | ----------------------------------------------------- |
# | NC_007605.1      | GCF_002402265.1           | Human gammaherpesvirus 4 (Epstein-Barr virus)         |
# | NC_000898.1      | GCF_000846365.1           | Human betaherpesvirus 6B                              |
# | NC_001664.4      | GCF_000845685.2           | Human betaherpesvirus 6A                              |
# | NC_001716.2      | GCF_000848125.1           | Human betaherpesvirus 7                               |
# | NC_006273.2      | GCF_000845245.1           | Human betaherpesvirus 5                               |
# | NC_009333.1      | GCF_000838265.1           | Human gammaherpesvirus 8                              |
# | NC_045512.2      | GCF_009858895.2           | Severe acute respiratory syndrome-related coronavirus |
# | MN485971.1       | xx                        | HIV from Belgium ... GTF is hand curated              |
#
#   | RefSeq  Sequence | RefSeq assembly accession | Notes                                                        |
#   | ---------------- | ------------------------- | ------------------------------------------------------------ |
#   | NC_001806.2      | GCF_000859985.2           | [Human alphaherpesvirus 1 (Herpes simplex virus type 1)](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=10298&lvl=3&lin=f&keep=1&srchmode=1&unlock) (strain 17) |
#
#  | RefSeq  Sequence | RefSeq assembly accession | Notes                                                        |
#  | ---------------- | ------------------------- | ------------------------------------------------------------ |
#  | KT899744.1       | KT899744.1                | HSV-1 strain KOS                                             |
#  | MH636806.1       | MH636806.1                | MHV68 (Murine herpesvirus 68 strain WUMS)                    |
#
## you most probably dont need to change these
scriptsdir: "PIPELINE_HOME/workflow/scripts"
resourcesdir: "PIPELINE_HOME/resources"
fastas_gtfs_dir: "REFS_DIR"

# strand inference
infer_strandedness: true
infer_strandedness_threshold: 0.8
strandedness_column: "strandedness"

# Cutadapt parameters
cutadapt_min_length: 15
cutadapt_n: 5
cutadapt_max_n: 0.5
cutadapt_O: 5
cutadapt_q: 20

# kraken2 db
kraken2_db: "/standard/dremel_lab/workflows/reference_data/kraken2/kraken2_db"
kraken2_params: "--use-names --gzip-compressed --quick"

# STAR parameters
star_save_transcript_sam: false
star_alignTranscriptsPerReadNmax: 30000
star_flanksize: 15

# deepTools parameters
deeptools_normalize: "CPM"
deeptools_binSize: 10

# list out all containers to be used
containers:
  base: "docker://nciccbr/ccbr_ubuntu_base_20.04:v7"
  bedToBigBed: "docker://seqinfomics/bedtobigbed:latest"
  bowtie1: "docker://nciccbr/charlie_bowtie1:v0.1.1"
  circexplorer: "docker://nciccbr/ccbr_circexplorer:v1.0"
  circRNA_finder: "docker://nciccbr/charlie_circrna_finder:v1.0.1"
  ciri: "docker://nciccbr/charlie_ciri2:v1.0.1"
  clear: "docker://nciccbr/ccbr_clear:v2.0.1"
  cutadapt: "docker://nciccbr/charlie_cutadapt_fqfilter:v1.0.1"
  deeptools: "docker://stjudecloud/deeptools:1.0.1"
  dcc: "docker://nciccbr/charlie_dcc:v0.2.1"
  fastqc: "docker://nciccbr/ccrgb_qctools:v4.0"
  gffread: "docker://zavolab/gffread:0.11.7"
  gtfToGenePred: "docker://seqinfomics/gtftogenepred:latest"
  genePredToBed: "docker://seqinfomics/genepredtobed:latest"
  kraken2: "docker://staphb/kraken2:2.1.3"
  mapsplice: "docker://cgrlab/mapsplice2:latest"
  multiqc: "docker://multiqc/multiqc:v1.28"
  picard: "docker://nciccbr/ccbr_picard_2.27.5:v1"
  qualimap: "docker://stjudecloud/qualimap:1.0.3"
  R: "docker://nciccbr/ccbr_r_4.3.0:v1"
  rseqc: "docker://clinicalgenomics/rseqc:4.0.0"
  samtools: "docker://staphb/samtools:1.21"
  star: "docker://nciccbr/ccbr_star_2.7.6a:latest"
  star_ucsc_cufflinks: "docker://nciccbr/charlie_star_ucsc_cufflinks:v0.4.1"
